### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by josephgupkim** [beam16/prj-rev-bwfs-dasmoto#4]
Your project looks great! It's nearly identical to the design spec minus the "height" attribute on the header that says "Dasmoto's Arts & Crafts".

Just remember to use indentations correctly and consistently as it is an invaluable habit to have as a developer. Other than that, amazing job on this project!

Grade: Meets expectation!

**Comment by beam16** [comment]
Thank you! I read more on indenting to make sure I do it correctly next time around. And when I removed the height attribute everything stayed the same, can't remember why I put it there in the first place... Thanks!
